# Site settings
title: 78MHz
email: masaki.seizaemon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  ゲーム制作物置き場&技術的備忘録
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nitoriytek.github.io" # the base hostname & protocol for your site
twitter_username: nitoriYTEk
github_username:  nitoriYTEk

# Build settings
markdown: kramdown
